export const genderColor: Record<string, any> = {
  '': 'default',
  '🤵 Erkak': 'primary',
  '🤵 Мужской': 'primary',
  '👩‍🦰 Женский': 'error',
  '👩‍🦰 Ayol': 'error',
  '👩‍🦰 Female': 'error',
  '🤵 Male': 'primary',
  '🤵 Erkek': 'primary',
  '👩‍🦰 Háyel': 'error',
};
export const gender: Record<string, any> = {
  '🤵 Erkak': 'Erkak',
  '🤵 Мужской': 'Мужской',
  '👩‍🦰 Женский': 'Женский',
  '👩‍🦰 Ayol': 'Ayol',
  '👩‍🦰 Female': 'Female',
  '🤵 Male': 'Male',
  '🤵 Erkek': 'Erkek',
  '👩‍🦰 Háyel': 'Háyel',
};

export const occupation: Record<string, any> = {
  '🏫 Maktab': 'Maktab',
  '🏫 School': 'School',
  '🏫 Школа': 'Школа',
  '🏫 Mektep': 'Mektep',
  '🎓 Universitet': 'OTM',
  '🎓 Unsiversty': 'Unsiversty',
  '🎓 Университет': 'Университет',
  '🏢 Kollej/texnikum': 'Kollej/texnikum',
  '🏢 College/Technikum': 'College/Technikum',
  '🏢 Колледж/Техникум': 'Колледж/Техникум',
  '💼 Boshqa': 'Boshqa',
  '💼 Basqa': 'Basqa',
  '💼 Другой': 'Другой',
  '💼 Another': 'Another',
};
export const occupationColor: Record<string, any> = {
  '': 'default',
  '🏫 Maktab': 'warning',
  '🏫 School': 'warning',
  '🏫 Школа': 'warning',
  '🏫 Mektep': 'warning',
  '🎓 Universitet': 'success',
  '🎓 Unsiversty': 'success',
  '🎓 Университет': 'success',
  '🏢 Kollej/texnikum': 'success',
  '🏢 College/Technikum': 'success',
  '🏢 Колледж/Техникум': 'success',
  '💼 Boshqa': 'secondary',
  '💼 Basqa': 'secondary',
  '💼 Другой': 'secondary',
  '💼 Another': 'secondary',
};
